name: district_wheels1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  flutter_dotenv: ^5.1.0 # Added flutter_dotenv here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# --- NEW: App Icon Configuration ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFD301" # Your brand yellow
  adaptive_icon_foreground: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env # Added .env to assets so your app can read it
    - images/
    - images/ybg.png
    - images/carbg.png
    - images/slide1.jpg
    - images/slide2.jpg
    - images/logo.png

  fonts:
    - family: HelveticaNow
      fonts:
        - asset: assets/fonts/HelveticaNow-Black.ttf
          weight: 900
    - family: Garet
      fonts:
        - asset: assets/fonts/Garet-Regular.otf
        - asset: assets/fonts/Garet-Bold.otf
          weight: 700
